name: go_on_time
description: "go on time"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_local_notifications: ^19.3.0
  geolocator: ^14.0.2
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_messaging: ^15.2.9
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.4
  intl: ^0.20.2
  workmanager: ^0.7.0
  geocoding: ^4.0.0
  firebase_auth: ^5.7.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/.env